"""
SecurePythonREPL - Sandboxed Python execution for LLM-generated code.

Uses RestrictedPython to safely execute code generated by the LLM,
preventing access to dangerous operations while allowing document navigation.
"""

from __future__ import annotations

import logging
import sys
from dataclasses import dataclass
from io import StringIO
from typing import Any

from RestrictedPython import compile_restricted, safe_globals
from RestrictedPython.Eval import default_guarded_getattr, default_guarded_getitem
from RestrictedPython.Guards import (
    full_write_guard,
    guarded_iter_unpack_sequence,
    guarded_unpack_sequence,
)

logger = logging.getLogger(__name__)


@dataclass
class REPLResult:
    """Result of code execution in the REPL."""

    success: bool
    output: str | None = None
    error: str | None = None
    return_value: Any = None


class SecurePythonREPL:
    """
    A secure Python REPL using RestrictedPython.

    Allows safe execution of LLM-generated code for document navigation
    while preventing dangerous operations like file system access,
    network calls, or code execution escape.
    """

    # Allowed built-in functions (safe subset)
    ALLOWED_BUILTINS = {
        # Type constructors
        "bool": bool,
        "dict": dict,
        "float": float,
        "int": int,
        "list": list,
        "set": set,
        "str": str,
        "tuple": tuple,
        # Iterators and generators
        "enumerate": enumerate,
        "filter": filter,
        "iter": iter,
        "len": len,
        "map": map,
        "max": max,
        "min": min,
        "next": next,
        "range": range,
        "reversed": reversed,
        "sorted": sorted,
        "sum": sum,
        "zip": zip,
        # String operations
        "chr": chr,
        "ord": ord,
        "repr": repr,
        # Math
        "abs": abs,
        "divmod": divmod,
        "pow": pow,
        "round": round,
        # Logic
        "all": all,
        "any": any,
        # Type checking
        "isinstance": isinstance,
        "issubclass": issubclass,
        "type": type,
        "callable": callable,
        "hasattr": hasattr,
        "getattr": getattr,
        # Printing (captured)
        "print": print,
        # None, True, False
        "None": None,
        "True": True,
        "False": False,
    }

    # Explicitly forbidden - these are never allowed
    FORBIDDEN = {
        "eval",
        "exec",
        "compile",
        "open",
        "input",
        "__import__",
        "globals",
        "locals",
        "vars",
        "dir",
        "delattr",
        "setattr",
        "breakpoint",
        "exit",
        "quit",
    }

    def __init__(self, max_output_size: int = 100000, timeout_seconds: int = 30):
        """
        Initialize the secure REPL.

        Args:
            max_output_size: Maximum size of captured output
            timeout_seconds: Execution timeout (not yet implemented)
        """
        self.max_output_size = max_output_size
        self.timeout_seconds = timeout_seconds
        self._globals: dict[str, Any] = {}
        self._locals: dict[str, Any] = {}
        self.reset()

    def reset(self) -> None:
        """Reset the REPL state."""
        self._globals = self._create_safe_globals()
        self._locals = {}

    def _create_safe_globals(self) -> dict[str, Any]:
        """Create a safe globals dictionary for execution."""
        safe = safe_globals.copy()

        # Add allowed builtins
        safe["__builtins__"] = self.ALLOWED_BUILTINS.copy()

        # Add RestrictedPython guards
        safe["_getattr_"] = default_guarded_getattr
        safe["_getitem_"] = default_guarded_getitem
        safe["_write_"] = full_write_guard
        safe["_iter_unpack_sequence_"] = guarded_iter_unpack_sequence
        safe["_unpack_sequence_"] = guarded_unpack_sequence

        # Add safe imports
        safe["re"] = self._get_safe_re()
        safe["json"] = self._get_safe_json()
        safe["math"] = self._get_safe_math()
        safe["collections"] = self._get_safe_collections()

        return safe

    def _get_safe_re(self) -> Any:
        """Get a restricted version of the re module."""
        import re

        class SafeRe:
            """Safe regex operations."""

            compile = staticmethod(re.compile)
            match = staticmethod(re.match)
            search = staticmethod(re.search)
            findall = staticmethod(re.findall)
            finditer = staticmethod(re.finditer)
            sub = staticmethod(re.sub)
            split = staticmethod(re.split)
            IGNORECASE = re.IGNORECASE
            MULTILINE = re.MULTILINE
            DOTALL = re.DOTALL

        return SafeRe()

    def _get_safe_json(self) -> Any:
        """Get a restricted version of the json module."""
        import json

        class SafeJson:
            """Safe JSON operations."""

            loads = staticmethod(json.loads)
            dumps = staticmethod(json.dumps)

        return SafeJson()

    def _get_safe_math(self) -> Any:
        """Get the math module (mostly safe)."""
        import math

        return math

    def _get_safe_collections(self) -> Any:
        """Get safe collections."""
        from collections import Counter as _Counter
        from collections import defaultdict as _defaultdict
        from collections import namedtuple as _namedtuple

        class SafeCollections:
            Counter = _Counter
            defaultdict = _defaultdict
            namedtuple = staticmethod(_namedtuple)

        return SafeCollections()

    def set_variable(self, name: str, value: Any) -> None:
        """
        Set a variable in the REPL namespace.

        Args:
            name: Variable name
            value: Variable value
        """
        if name.startswith("_"):
            raise ValueError(f"Cannot set private variable: {name}")
        self._locals[name] = value

    def get_variable(self, name: str) -> Any:
        """
        Get a variable from the REPL namespace.

        Args:
            name: Variable name

        Returns:
            Variable value or None if not found
        """
        return self._locals.get(name)

    def execute(self, code: str) -> REPLResult:
        """
        Execute Python code in the secure sandbox.

        Args:
            code: Python code to execute

        Returns:
            REPLResult with success status, output, and any errors
        """
        # Basic sanitization
        code = code.strip()
        if not code:
            return REPLResult(success=True, output="")

        # Check for forbidden patterns
        for forbidden in self.FORBIDDEN:
            if forbidden in code:
                return REPLResult(
                    success=False,
                    error=f"Forbidden operation: {forbidden}",
                )

        # Compile with RestrictedPython
        try:
            byte_code = compile_restricted(
                code,
                filename="<repl>",
                mode="exec",
            )

            if byte_code.errors:
                return REPLResult(
                    success=False,
                    error=f"Compilation errors: {byte_code.errors}",
                )

        except SyntaxError as e:
            return REPLResult(
                success=False,
                error=f"Syntax error: {e}",
            )
        except Exception as e:
            return REPLResult(
                success=False,
                error=f"Compilation failed: {type(e).__name__}: {e}",
            )

        # Capture stdout
        old_stdout = sys.stdout
        sys.stdout = captured_output = StringIO()

        try:
            # Execute the code
            exec(byte_code.code, self._globals, self._locals)

            # Get captured output
            output = captured_output.getvalue()
            if len(output) > self.max_output_size:
                output = output[: self.max_output_size] + "\n... (output truncated)"

            return REPLResult(
                success=True,
                output=output if output else None,
            )

        except Exception as e:
            return REPLResult(
                success=False,
                error=f"{type(e).__name__}: {e}",
            )

        finally:
            sys.stdout = old_stdout

    def execute_expression(self, expression: str) -> REPLResult:
        """
        Evaluate a Python expression and return its value.

        Args:
            expression: Python expression to evaluate

        Returns:
            REPLResult with the expression's value
        """
        expression = expression.strip()
        if not expression:
            return REPLResult(success=True, return_value=None)

        # Compile as expression
        try:
            byte_code = compile_restricted(
                expression,
                filename="<expr>",
                mode="eval",
            )

            if byte_code.errors:
                return REPLResult(
                    success=False,
                    error=f"Compilation errors: {byte_code.errors}",
                )

        except SyntaxError as e:
            return REPLResult(
                success=False,
                error=f"Syntax error: {e}",
            )
        except Exception as e:
            return REPLResult(
                success=False,
                error=f"Compilation failed: {type(e).__name__}: {e}",
            )

        try:
            result = eval(byte_code.code, self._globals, self._locals)
            return REPLResult(
                success=True,
                return_value=result,
            )

        except Exception as e:
            return REPLResult(
                success=False,
                error=f"{type(e).__name__}: {e}",
            )


class UnsafePythonREPL:
    """
    An unrestricted Python REPL for trusted environments.

    WARNING: Only use this when you trust the code source completely.
    This should NOT be used with LLM-generated code in production.
    """

    def __init__(self, max_output_size: int = 100000):
        self.max_output_size = max_output_size
        self._namespace: dict[str, Any] = {}

    def reset(self) -> None:
        """Reset the REPL state."""
        self._namespace = {}

    def set_variable(self, name: str, value: Any) -> None:
        """Set a variable in the namespace."""
        self._namespace[name] = value

    def get_variable(self, name: str) -> Any:
        """Get a variable from the namespace."""
        return self._namespace.get(name)

    def execute(self, code: str) -> REPLResult:
        """Execute code without restrictions."""
        code = code.strip()
        if not code:
            return REPLResult(success=True, output="")

        old_stdout = sys.stdout
        sys.stdout = captured_output = StringIO()

        try:
            exec(code, self._namespace)
            output = captured_output.getvalue()
            if len(output) > self.max_output_size:
                output = output[: self.max_output_size] + "\n... (output truncated)"

            return REPLResult(success=True, output=output if output else None)

        except Exception as e:
            return REPLResult(
                success=False,
                error=f"{type(e).__name__}: {e}",
            )

        finally:
            sys.stdout = old_stdout
